# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set -g mouse on

set -g status-interval 5
# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

set-window-option -g mode-keys vi

# switch panes using Alt-arrow without prefix, I'm disabling them in nvim anyway
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind C-h select-pane -L
bind C-l select-pane -R
bind C-k select-pane -U
bind C-j select-pane -D

# Display in full colour
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -a terminal-features "xterm:Tc"
# set -g default-terminal "xterm-256color"
# set -ag terminal-overrides ",xterm-256color:Tc"

set -g focus-events on
set -sg escape-time 10

# Theming

# List of TPM plugins

# set -g @plugin 'catppuccin/tmux'
# set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha

set -g @plugin "erikw/tmux-powerline"

# tmux-resurrect, to save and restore sessions
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @resurrect-strategy-nvim "session"
set -g @resurrect-capture-pane-contents "on"
set -g @continuum-save-interval "5"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @continuum-boot "on"

# run-shell "powerline-daemon -q"
# source "/usr/share/powerline/bindings/tmux/powerline.conf"


# Run the tmux plugin manager (This line stays at the bottom!)
run '~/.config/tmux/plugins/tpm/tpm'
